### ISSUE TITLE
Interaction Checklist

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/iiifManifestLayouts#10]
- [ ] As a user, I want to see a sequence of a iiif manifest laid out on an openseadragon canvas, with labels for the canvases, and spacing indicative of the object's structure. A book should have pages paired, a scroll should have segments seamlessly stitched together. 
- [x] When I click on an item in the manifest collection, I want to zoom in to see it better, and have more detail loaded. Clicking an opening in a book should zoom in on the opening, clicking a notable area of a scroll should zoom into that part of the scroll. 
- [x] When going from an overview to a particular item, the labels and any interaction hints like image borders or highlights should disappear as I am zooming in.

**Comment by mejackreed** [comment]
One question.. Is this layout scheme going to be coupled to OSD? It seems that the layout could be useful decoupled form OSD?

**Comment by aeschylus** [comment]
The layout is decoupled entirely from OSD, in a separate module. I will make it accessible through the component's API.

**Comment by mejackreed** [comment]
:+1:

**Comment by aeschylus** [comment]
Check out the release. I am pairing with Ian at 3:00 today to get through the final details for a useful version, but take a look, and if you have time let's meet after lunch to talk about whether the API is what we need. To see what's exposed, check out [these lines](https://github.com/aeschylus/iiifManifestLayouts/blob/master/src/main.js#L401-L410). 

Similar to what we've talked about previously, these functions will only perform the operations allowed by the component's internals. This will allow us to build a lightweight event wrapper (like the store data flow control) around it. Ideally there must be no persistent internal state to get out of sync. One operation that hasn't been built to ensure this is the ability to refresh the entire manifest. We also need something that might be called a "viewObject" or "displayFilter" that can tell which detail images or alternate images are shown or hidden, and what their opacity and http request status is.
